In [1]:
import numpy as np

In [2]:
#1. Create a null vector of size 10 but the fifth value which is 1.

vec1 = np.zeros(10)
vec1[4] = 1
vec1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [3]:
#2. Create a vector with values ranging from 10 to 49.

vec2 = np.arange(10,50)
vec2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#3. Create a 3x3 matrix with values ranging from 0 to 8

mat1 = np.random.randint(0,8,(3,3))
mat1

array([[6, 1, 2],
       [5, 1, 2],
       [7, 4, 1]])

In [5]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

a = np.nonzero([1,2,0,0,4,0])
a

(array([0, 1, 4], dtype=int64),)

In [6]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.

b = np.random.randn(10,10)
print(b)
print("maximum value",np.max(b))
print("minimum value",np.min(b))

[[-1.29573808  0.5259469   0.12242166  1.47272828  1.45242245 -1.70383434
   0.25454488 -0.26166459 -0.45677104  0.74180865]
 [-0.44500792  0.06930621 -0.98067566  1.1617314   1.13887143  0.99773993
   1.92411099  0.5564398   0.66925711  0.46928885]
 [-0.84151762 -0.57117294  1.90734078  0.95606951  0.81937976 -0.26174917
   0.98587907  1.35869849 -1.33012562 -2.07378515]
 [ 1.24015384  0.25775859  1.89967819 -0.24300482  0.68038616  1.70428959
  -1.18974055  1.20645332 -1.44438259 -0.71599609]
 [ 0.22312015 -0.41354018  0.05685132  1.28635617 -0.60743574  0.04791096
  -1.75137486 -1.65444306 -1.74595958 -1.22674517]
 [-0.10444793  1.29373895 -2.21724276 -1.61622439  0.80595661 -1.16744727
   0.08526796  0.39811872  1.1682867   1.25812265]
 [ 0.13423481  0.58974494  1.68517549  0.15171521  0.49041254 -0.24206429
   1.38514446  1.09896039 -1.09861682  0.52859624]
 [-0.05320087  0.30726535 -0.50523115 -0.60181856  0.04436163 -0.26908712
   0.93903393 -0.12232089  0.21217685  0.77337477]


In [8]:
#6. Create a random vector of size 30 and find the mean value.

c = np.random.rand(30)
print(c)
c.mean()

[0.94984899 0.62392383 0.24873782 0.81913083 0.48702473 0.10387112
 0.67343162 0.31363823 0.23463649 0.91957035 0.76337847 0.45970417
 0.82760261 0.86303273 0.95388504 0.26584895 0.2715684  0.25391363
 0.5729291  0.44780329 0.13969617 0.21543108 0.00648482 0.99130742
 0.9520952  0.0448866  0.79973748 0.75081005 0.86824741 0.34186062]


0.5388012413703591